service: momsbot

provider:
   name: aws
   runtime: nodejs12.x
   memorySize: 512
   timeout: 15
   region: us-east-2
functions:
     api:
       handler: lambda.handler
       events:
#        - http: ANY {proxy+}
#        - http: ANY /
         - http:
             path: /
             method: post
